# Comparing Strings

There are many ways in which one may compare two or more strings. Typical goals of such comparisions are to indicate how similar (or dissimilar) two strings are. This is typically done by defining a **metric** (or **distance**) between two words. 

In this notebook we consider several ways to compare strings. These are well-known distances such as the **Hamming** distance, **longest common subsequence**, among others. 

## Longest Common Subsequence (LCS) and Minimum Edit Distance


In [90]:
import numpy as np

M = "fence"
N = "wicked"

m = len(M)
n = len(N)

dp = np.full((m, n), 0)

# init base cases
dp[0][0] = 0

    
ED_helper(m-1,n-1)
print(dp)


[[0 0 0 0 0 0]
 [0 2 3 4 5 0]
 [0 3 4 5 6 5]
 [0 4 5 6 7 6]
 [0 0 0 5 6 7]]


In [89]:
def ED_helper(i,j):
    if dp[i][j] == 0:
        
        if i == 0:
            return j
        elif j == 0:
            return i
        elif M[i-1] == N[j-1]:
            dp[i][j] = ED_helper(i-1, j-1)
            
        else:
            dp[i][j] = 1 + np.minimum(ED_helper(i, j-1), ED_helper(i-1, j))
        
    return dp[i][j]